#pragma once

class UserConfigInfo
{
	SHARED_SINGLETON(UserConfigInfo);

public:
	UserConfigInfo();
	~UserConfigInfo();

	/* to fix */

	int getArenaOrbNotification(void) const;
	int getAutoBattle(void) const;
	int getAutoBb(void) const;
	int getAutoOpenTreasure(void) const;
	int getAutoOptionDispFlg(void) const;
	int getAutoSBb(void) const;
	int getBattleSpeed(void) const;
	int getBbCutin(void) const;
	int getBgmVol(void) const;
	int getBgmVolPer(void) const;
	int getDailytaskNotification(void) const;
	int getDispBattleEffect(void) const;
	int getDispBgEffect(void) const;
	int getDispSkillInfo(void) const;
	int getDrawSparkDisp(void) const;
	int getDrawSparkDispPer(void) const;
	int getDropItemDisp(void) const;
	int getDropItemDispPer(void) const;
	int getEnergyNotification(void) const;
	int getGrowthPushMode(void) const;
	int getGuildContribNotification(void) const;
	int getItemCnt(void) const;
	int getLobiChatOpenFlag(void) const;
	int getMaxDrawSparkDisp(void) const;
	int getMaxDropItemDisp(void) const;
	int getMinDropItemDispPer(void) const;
	int getMultiAutoOrbUse(void) const;
	int getOnceDropItemDisp(void) const;
	int getPartyEditDispMode(void) const;
	int getPermitGuildInvitation(void) const;
	int getRecArenaMode(void) const;
	int getRecCampaignMode(void) const;
	int getRecFhMode(void) const;
	int getRecFrogateMode(void) const;
	int getRecLibraryMode(void) const;
	int getRecMicFlag(void) const;
	int getRecMissionMode(void) const;
	int getRecMode(void) const;
	int getRecRaidMode(void) const;
	int getRecTrialMode(void) const;
	int getRecWindow(void) const;
	int getSeVol(void) const;
	int getSeVolPer(void) const;
	int getTargetPriority(void) const;
	int getTurnInfoDisp(void) const;
	int getVideoReplayMode(void) const;
	int getdeviceSupportedForVideoRecording(void) const;
	int isAutoBB(void) const;
	int isAutoLoot(void) const;
	int isGraphicsQualityLow(void) const;
	int isHealPriority(void) const;
	int isOverdriveUltimateBBPriority(void) const;
	int isRecArena(void) const;
	int isRecFH(void) const;
	int isRecMission(void) const;
	int isRecRaid(void) const;
	int isRecTrial(void) const;
	int isSuperBBPriority(void) const;
	int setArenaOrbNotification(bool) const;
	int setAutoBB(bool) const;
	int setAutoBattle(int) const;
	int setAutoBb(int) const;
	int setAutoLoot(bool) const;
	int setAutoOpenTreasure(int) const;
	int setAutoOptionDispFlg(int) const;
	int setAutoSBb(int) const;
	int setBattleSpeed(int) const;
	int setBbCutin(int) const;
	int setBgmVol(int) const;
	int setDailytaskNotification(bool) const;
	int setDispBattleEffect(int) const;
	int setDispBgEffect(int) const;
	int setDispSkillInfo(int) const;
	int setDrawSparkDisp(int) const;
	int setDropItemDisp(int) const;
	int setEnergyNotification(bool) const;
	int setGrowthPushMode(int) const;
	int setGuildContribNotification(bool) const;
	int setHealPriority(bool) const;
	int setItemCnt(int) const;
	int setLobiChatOpenFlag(int) const;
	int setLowGraphicsQuality(bool) const;
	int setMultiAutoOrbUse(int) const;
	int setOnceDropItemDisp(int) const;
	int setOverdriveUltimateBBPriority(bool) const;
	int setPartyEditDispMode(int) const;
	int setPermitGuildInvitation(int) const;
	int setRecArenaMode(int) const;
	int setRecCampaignMode(int) const;
	int setRecFhMode(int) const;
	int setRecFrogateMode(int) const;
	int setRecLibraryMode(int) const;
	int setRecMicFlag(int) const;
	int setRecMissionMode(int) const;
	int setRecMode(int) const;
	int setRecRaidMode(int) const;
	int setRecTrialMode(int) const;
	int setRecWindow(int) const;
	int setSeVol(int) const;
	int setSuperBBPriority(bool) const;
	int setTargetPriority(int) const;
	int setTurnInfoDisp(int) const;
	int setVideoReplayMode(bool) const;
	int setdeviceSupportedForVideoRecording(bool) const;

};
